//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Prime95.rc
//
#define IDH_PRIMENET                    11
#define IDH_WORKER_THREADS              12
#define IDH_VACATION                    13
#define IDH_RANGE_STATUS                14
#define IDH_CONTINUE                    15
#define IDH_STOP                        16
#define IDH_APP_EXIT                    17
#define IDH_PASSWORD                    18
#define IDH_TEST                        19
#define IDH_TIME                        20
#define IDH_PMINUS1                     21
#define IDH_ECM                         22
#define IDH_SUMINP_ERRCHK               23
#define IDH_ERRCHK                      24
#define IDH_MANUALCOMM                  26
#define IDH_QUIT                        27
#define IDH_CPU                         28
#define IDH_PREFERENCES                 29
#define IDH_TORTURE                     31
#define IDH_TRAY                        32
#define IDH_HIDE                        33
#define IDH_SERVICE                     34
#define IDH_HELP_FINDER                 35
#define IDH_APP_ABOUT                   36
#define IDH_SERVER                      37
#define IDH_UNRESERVE                   38
#define IDH_WELCOME                     39
#define IDH_BENCHMARK                   40
#define IDD_ABOUTBOX                    100
#define IDD_RESOURCES                   101
#define IDD_ADVANCED_RESOURCES		102
#define IDR_HTML_TORTUREDLG             103
#define IDR_MAINFRAME                   128
#define IDR_MDITYPE                     129
#define IDD_TEST                        132
#define IDD_CPU                         133
#define IDC_CURSOR1                     133
#define IDD_TIME                        134
#define IDD_PREFERENCES                 135
#define IDC_CURSOR2                     135
#define IDC_AVX512                      136
#define IDC_CERT			136
#define IDC_FMA3                        137
#define IDC_AVX                         138
#define IDC_SSE2                        139
#define IDC_WEAKTORTUREGROUP            140
#define IDD_PRIMENET                    145
#define IDD_BENCHMARK                   146
#define IDD_MANUAL_COMM                 149
#define IDD_ECM                         150
#define IDD_PMINUS1                     152
#define IDI_YELLOW_ICON                 153
#define IDD_WELCOME                     153
#define IDD_UNRESERVE                   154
#define IDD_TORTURE                     155
#define IDR_TRAYMENU                    156
#define ID_OPEN_EXIT                    157
#define ID_TRAY_RESTORE                 158
#define IDD_WORKER_THREADS              160
#define IDD_PRIMENET_CONNECTION         161
#define IDD_WORKER_START                163
#define IDD_WORKER_STOP                 164
#define IDC_LL                          1000
#define IDC_NOISE                       1000
#define IDC_EDIT1                       1001
#define IDC_BACKUP                      1001
#define IDC_BATTERY                     1002
#define IDC_LIMIT_FFT_SIZES             1003
#define IDC_UPLOAD_BANDWIDTH_TEXT       1003
#define IDC_CORES_TEXT                  1004
#define IDC_UPLOAD_START_TEXT           1004
#define IDC_P                           1005
#define IDC_UPLOAD_END_TEXT             1005
#define IDC_DISK                        1006
#define IDC_TEMP_DIR                    1006
#define IDC_HOURS                       1007
#define IDC_P2                          1007
#define IDC_NETWORK                     1007
#define IDC_UPLOAD_BANDWIDTH            1007
#define IDC_ARCHIVE_DIR                 1007
#define IDC_MINFFT                      1008
#define IDC_R_ITER                      1008
#define IDC_UPLOAD_START		1008
#define IDC_P1                          1009
#define IDC_END_DATES                   1009
#define IDC_UPLOAD_END			1009
#define IDC_P3                          1010
#define IDC_MODEM                       1010
#define IDC_MEMORY                      1010
#define IDC_DOWNLOAD_MB			1010
#define IDC_MAXFFT                      1011
#define IDC_WORK                        1011
#define IDC_CERT_CPU_TEXT               1011
#define IDC_NUM_CURVES                  1012
#define IDC_TIMEFFT                     1012
#define IDC_ARCHIVE_DIR_TEXT            1012
#define IDC_THREAD                      1013
#define IDC_THREAD_TEXT                 1014
#define IDC_USERID                      1015
#define IDC_P4                          1015
#define IDC_P5                          1016
#define IDC_FACTOR                      1017
#define IDC_IN_PLACE_FFT                1017
#define IDC_COMPID                      1017
#define IDC_P6                          1017
#define IDC_ERRCHK                      1017
#define IDC_USERNAME                    1018
#define IDC_ALL_COMPLEX                 1018
#define IDC_CORES                       1019
#define IDC_HYPERTHREADING              1021
#define IDC_WORKERS_TEXT                1022
#define IDC_WORKGROUP                   1023
#define IDC_WORKERS                     1023
#define IDC_NETWORK_TEXT                1024
#define IDC_END_DATES_TEXT              1025
#define IDC_PRIMENET                    1026
#define IDC_MODEM_TEXT                  1026
#define IDC_WORK_TEXT                   1027
#define IDC_MINFFT_TEXT                 1027
#define IDC_ALL_FFT_IMPL                1028
#define IDC_COMPLETION                  1029
#define IDC_MEMORY_TEXT                 1029
#define IDC_PRIORITY                    1029
#define IDC_CERT_CPU			1030
#define IDC_MAXFFT_TEXT                 1030
#define IDC_TIMEFFT_TEXT                1031
#define IDC_DIALUP                      1033
#define IDC_MANUAL                      1035
#define IDC_NOW                         1036
#define IDC_HYPER_LL                    1037
#define IDC_HYPER_TF                    1038
#define IDC_THREADNUM_TEXT              1040
#define IDC_NUMCPUS_TEXT                1041
#define IDC_DAY_MEMORY_TEXT             1042
#define IDC_DAY_MEMORY                  1043
#define IDC_EMERGENCY_MEM		1044
#define IDC_NIGHT_MEMORY_TEXT           1048
#define IDC_NIGHT_MEMORY                1049
#define IDC_START_TIME_TEXT             1050
#define IDC_START_TIME                  1051
#define IDC_END_TIME_TEXT               1052
#define IDC_END_TIME                    1053
#define IDC_CPU_INFO                    1056
#define IDC_L2_CACHE                    1057
#define IDC_L3_CACHE                    1058
#define IDC_L4_CACHE                    1059
#define IDC_LARGE_FFT                   1060
#define IDC_BLEND                       1061
#define IDC_CUSTOM                      1062
#define IDC_LINK                        1067
#define IDC_APP_STRING                  1068
#define IDC_WARN1                       1070
#define IDC_WARN2                       1071
#define IDC_WARN3                       1072
#define IDC_WORK_TYPE_TEXT              1073
#define IDC_COMBO1                      1075
#define IDC_COMBO2                      1076
#define IDC_COMBO3                      1077
#define IDC_CONNECTION                  1078
#define IDC_NUMCPUS                     1078
#define IDC_PROXYHOST                   1079
#define IDC_PROXYPORT_TEXT              1080
#define IDC_PROXYPORT                   1081
#define IDC_PROXYUSER_TEXT              1082
#define IDC_PROXYUSER                   1083
#define IDC_PROXYPASSWORD_TEXT          1084
#define IDC_PROXYPASSWORD               1085
#define IDC_DEBUG                       1086
#define IDC_RADIO1                      1087
#define IDC_ADVANCED                    1088
#define IDM_CONTINUE_SWITCHER           32770
#define IDM_CONTINUE                    32771
#define IDM_STOP_SWITCHER               32772
#define IDM_STOP                        32773
#define IDM_ERRCHK                      32775
#define IDM_TEST                        32777
#define IDM_TIME                        32778
#define IDM_RESOURCES                   32780
#define IDM_PREFERENCES                 32781
#define IDM_CPU                         32782
#define IDM_STATUS                      32783
#define IDM_TRAY                        32788
#define IDM_HIDE                        32789
#define IDM_TORTURE                     32790
#define IDM_WORKER_THREADS              32791
#define IDM_PRIMENET                    32792
#define IDM_SERVER                      32794
#define IDM_QUIT                        32795
#define IDM_SERVICE                     32797
#define IDM_MANUALCOMM                  32798
#define IDM_ECM                         32799
#define IDM_PMINUS1                     32801
#define IDM_UNRESERVE                   32805
#define USR_WELCOME                     32806
#define IDM_BENCHMARK                   32807
#define IDM_TRAY_OPEN                   32808
#define USR_SERVICE_STOP                32809
#define IDM_STOP_CONTINUE               32810
#define USR_TORTURE                     32811
#define USR_SCROLL                      32812
#define USR_TITLE                       32813
#define USR_ICON                        32814
#define IDM_MERGE_MAIN                  32815
#define IDM_MERGE_COMM                  32816
#define IDM_MERGE_ALL                   32817
#define IDM_HELP_FORUM                  32818
#define IDM_HELP_WIKI                   32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
